-- Proposals — full proposal records generated by the intake agent
CREATE TABLE IF NOT EXISTS proposals (
  id                   UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  prospect_name        TEXT          NOT NULL,
  prospect_email       TEXT          NOT NULL,
  industry             TEXT,
  locations            INTEGER       DEFAULT 1,
  monthly_leads        INTEGER,
  platform             TEXT,
  platform_tier        TEXT,
  integrations_detected JSONB        NOT NULL DEFAULT '[]'::jsonb,
  recommended_package  TEXT,
  setup_total          NUMERIC(10,2),
  monthly_total        NUMERIC(10,2),
  goals                JSONB         NOT NULL DEFAULT '[]'::jsonb,
  proposal_pdf_url     TEXT,
  status               TEXT          NOT NULL DEFAULT 'draft'
                         CHECK (status IN ('draft', 'sent', 'viewed', 'accepted', 'declined', 'expired')),
  crm_deal_id          TEXT
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_proposals_prospect_email ON proposals(prospect_email);
CREATE INDEX IF NOT EXISTS idx_proposals_status        ON proposals(status);
CREATE INDEX IF NOT EXISTS idx_proposals_created_at    ON proposals(created_at DESC);

-- RLS
ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;

-- Service role can do everything; all other roles denied by default
CREATE POLICY "service_role_all" ON proposals
  FOR ALL USING (auth.role() = 'service_role');
