name: Build Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: dist/
          retention-days: 90
      
      - name: Create build summary
        run: |
          echo "## ✅ Build Successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Next Steps:" >> $GITHUB_STEP_SUMMARY
          echo "1. Download the 'website-dist' artifact below" >> $GITHUB_STEP_SUMMARY
          echo "2. Unzip the downloaded file" >> $GITHUB_STEP_SUMMARY
          echo "3. Upload contents to Supabase Storage" >> $GITHUB_STEP_SUMMARY
          echo "4. Visit https://www.adamsilvaconsulting.com/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Build completed at: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
